apiVersion: v1
kind: Service
metadata:
  name: todo-api
spec:
  type: {{ .Values.service.backendType }}
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      {{- if and (eq .Values.service.backendType "NodePort") .Values.service.backendNodePort }}
      nodePort: {{ .Values.service.backendNodePort }}
      {{- end }}
