apiVersion: v1
kind: Service
metadata:
  name: todolist-vue
spec:
  type: {{ .Values.service.frontendType }}
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
