apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "todo-chart.fullname" . }}-mariadb
spec:
  serviceName: {{ .Values.database.mysqlHost | quote }}
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: {{ .Values.images.database }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "todo-chart.fullname" . }}-db-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: {{ .Values.database.mysqlDb | quote }}
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "todo-chart.fullname" . }}-db-pvc
