apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "todo-chart.fullname" . }}-db-policy
spec:
  podSelector:
    matchLabels:
      app: mariadb 
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: todo-backend 
    ports:
    - protocol: TCP
      port: 3306